### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by soyscp** [yosseferrazik/generic-logs#1]
No funciona en Typescript. Estaría bien que lo hiciese.

```ts
Could not find a declaration file for module 'generic-logs'. 'c:/Users/user/X/X/X/node_modules/generic-logs/index.js'
implicitly has an 'any' type.
Try `npm i --save-dev @types/generic-logs` if it exists or add a new declaration (.d.ts) file containing
`declare module 'generic-logs';` ts(7016)
```
¡Gracias por adelantado!

**Comment by soyscp** [comment]
Merging #2 will fix the issue.

**Comment by gatomod** [comment]
@SCP1939 @types definitions only works if definitions are available in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Since this package is new and not much popular there are not. 
As you said above, that PR will fix the issue.
